version: '3.3'

services:
  vanilla:
    image: itzg/minecraft-server
    ports:
      - 25566:25565
    volumes:
      - /docker/minecraft-vanilla:/data
    deploy:
      placement:
        constraints:
          - node.labels.storage==yes
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      RCON_PORT: 25575
      VERISON: "LATEST"
      
  snapshot:
    image: itzg/minecraft-server
    ports:
      - 25567:25565
    volumes:
      - /docker/minecraft-snapshot:/data
    deploy:
      placement:
        constraints:
          - node.labels.storage==yes
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      RCON_PORT: 25575
      VERSION: "SNAPSHOT"
      
  forge:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    volumes:
      - /docker/minecraft-forge:/data
    deploy:
      placement:
        constraints:
          - node.labels.storage==yes
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      RCON_PORT: 25575
      TYPE: "FORGE"
      VERSION: "LATEST"
      
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - /docker/minecraft-rcon:/opt/rcon-web-admin/db"
